# Generated by Django 5.0.4 on 2024-04-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="plan",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
