# Generated by Django 5.0.4 on 2024-04-12 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csc", "0002_flat_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="floor",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="padic",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="year",
        ),
        migrations.AddField(
            model_name="flat",
            name="price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="цена",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="img",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="фото дома"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="img",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="картинка"
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="квартир в продаже",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flats",
                to="csc.house",
                verbose_name="литер",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="numbers",
            field=models.IntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="номер дома",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="plan",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="план-схема"
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="rooms",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="square",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(20)],
                verbose_name="площадь",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="flatss",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="количество квартир",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="floors",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="количество этажей",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="house",
            field=models.IntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="номер дома",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="padics",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="количество подьездов",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="year",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(2015)],
                verbose_name="год сдачи",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="text",
            field=models.TextField(verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=64, unique=True, verbose_name="название"),
        ),
    ]
