# Generated by Django 5.0.4 on 2024-04-12 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csc", "0003_remove_flat_floor_remove_flat_padic_remove_flat_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="price_for_metr",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="цена за квадратный метр",
            ),
        ),
    ]
