# Generated by Django 5.0.4 on 2024-04-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csc", "0004_flat_price_for_metr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="price_for_metr",
        ),
    ]
