# Generated by Django 5.0.4 on 2024-04-19 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csc", "0006_alter_flat_options_alter_house_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_col", models.IntegerField(verbose_name="количество комнат")),
            ],
            options={
                "verbose_name": "комната",
                "verbose_name_plural": "комнаты",
                "ordering": ["room_col"],
            },
        ),
        migrations.RemoveField(
            model_name="flat",
            name="numbers",
        ),
        migrations.AlterField(
            model_name="flat",
            name="rooms",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="csc.room",
                verbose_name="комнаты",
            ),
        ),
    ]
