# Generated by Django 5.0.4 on 2024-04-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csc", "0007_room_remove_flat_numbers_alter_flat_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="rooms",
            field=models.IntegerField(verbose_name="комнаты"),
        ),
    ]
