# Generated by Django 5.0.4 on 2024-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csc", "0010_alter_flat_rooms_delete_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
            ],
        ),
    ]
