# Generated by Django 5.0.4 on 2024-05-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csc", "0012_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
