# Generated by Django 5.0.4 on 2024-05-15 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csc", "0013_review_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.IntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="количество комнат",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="flat",
            name="rooms",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="csc.room",
                verbose_name="количество комнат",
            ),
        ),
    ]
